version: '3.8'

services:
  app:
    build: .
    container_name: salon_app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/salonApp
    volumes:
      - .:/app
      - /app/node_modules

  mongo:
    image: mongo
    container_name: salon_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: